### PR TITLE
auto download civitai model

### PR DESCRIPTION
**Pull request by phineas-pta**
solve #2

### CODE REVIEW

**Comment by phineas-pta** [comment]
wait a sec, i want to figure out how to add progress bar

**Comment by phineas-pta** [comment]
it should be good now, 3 packages `requests` `werkzeug` `tqdm` already included in dependencies

**Comment by oneir0mancer** [comment]
I'm gonna clean up a little, and let diffusers handle cases when you put huggingface model_id or local path into url field.

**Comment by phineas-pta** [comment]
oh i just realize u can also reuse the function to download lora embedding vae from civitai, maybe an UI to download those things ?

**Comment by oneir0mancer** [comment]
Yes, it would make sense to move this function to some utility class to be able to use it from anywhere.

Not sure about UI for downloading. Embeddings - maybe, but you can just upload them manually and put into the folder. Vae - you will have to also run the script for conversion, I don't think Diffusers can handle just vae automatically.

As for loras, it makes sense to make UI for handling them as well, like calling `pipe.fuse_lora()`, `pipe.unfuse_lora()`, keeping track of scale, etc. And I'm honestly not sure if it's worth the effort, I find it easier to just do it through code.

**Pull request merged**
